#!/bin/sh

# Niceties
alias p="sudo pacman"
alias h="htop"
alias ls="lsd"
alias yay="yay --sudoloop"
alias icat="kitty +kitten icat"
# This is to be able to work with modern terminal emulators through ssh
alias ssh="TERM=xterm-256color ssh"

# Fun
alias starwars="telnet towel.blinkenlights.nl"

# Docker
alias dcrun="sudo docker-compose run --rm"
alias dcup="sudo docker-compose up"
alias dcdown="sudo docker-compose down"
alias dcbuild="sudo docker-compose build"
alias dclogs="sudo docker-compose logs"
alias dcpull="sudo docker-compose pull"

# Music
alias music="ncmpcpp"
alias pause="mpc toggle"
alias next="mpc next"
alias prev="mpc prev"

# File openners
alias -s {pdf,PDF}='background zathura'

# Utils

# Copying locally huge files
# -a is for archive, which preserves ownership, permissions etc.
# -v is for verbose, so I can see what's happening (optional)
# -h is for human-readable, so the transfer rate and file sizes are easier to read (optional)
# -W is for copying whole files only, without delta-xfer algorithm which should reduce CPU load
# --no-compress as there's no lack of bandwidth between local devices
# --progress so I can see the progress of large files (optional)
# Usage: supercp /src /dst
alias supercp="rsync -avhW --no-compress --progress"
