#!/bin/sh

# Niceties
alias p="sudo pacman"
alias h="htop"
alias ls="lsd"
alias icat="kitty +kitten icat"
alias cat="bat"
# This is to be able to work with modern terminal emulators through ssh
alias ssh="TERM=xterm-256color ssh"

# Fun
alias starwars="telnet towel.blinkenlights.nl"

# Docker
alias dc="sudo docker compose"
alias dcrun="dc run --rm"
alias dcup="dc up"
alias dcdown="dc down"
alias dcbuild="dc build"
alias dclogs="dc logs"
alias dcpull="dc pull"
alias dcps="dc ps"

# Music
alias music="ncmpcpp"
alias pause="mpc toggle"
alias next="mpc next"
alias prev="mpc prev"

# File openners
alias -s {pdf,PDF}='background zathura'
alias -s {jpg,JPG,jpeg,JPEG,png}='background sxiv'

# Utils

# Copying locally huge files
# -a is for archive, which preserves ownership, permissions etc.
# -v is for verbose, so I can see what's happening (optional)
# -h is for human-readable, so the transfer rate and file sizes are easier to read (optional)
# -W is for copying whole files only, without delta-xfer algorithm which should reduce CPU load
# --no-compress as there's no lack of bandwidth between local devices
# --progress so I can see the progress of large files (optional)
# Usage: supercp /src /dst
alias supercp="rsync -avhW --no-compress --progress"

# Extract file archives of various types
# Taken from https://ostechnix.com/a-bash-function-to-extract-file-archives-of-various-types/
extract () {
     if [ -f $1 ] ; then
         case $1 in
             *.tar.bz2)   tar xjf $1     ;;
             *.tar.gz)    tar xzf $1     ;;
             *.bz2)       bunzip2 $1     ;;
             *.rar)       unrar e $1       ;;
             *.gz)        gunzip $1      ;;
             *.tar)       tar xf $1      ;;
             *.tbz2)      tar xjf $1     ;;
             *.tgz)       tar xzf $1     ;;
             *.zip)       unzip $1       ;;
             *.Z)         uncompress $1  ;;
             *.7z)        7z x $1    ;;
             *)           echo "'$1' cannot be extracted via extract()" ;;
         esac
     else
         echo "'$1' is not a valid file"
     fi
}
