#!/bin/bash

# Check for arguments
if [[ $# -eq 0 ]]; then
    echo "No file specified"
    exit 1
fi

FILE=$1
NAME=${FILE%.*}
EXTENSION=${FILE##*.}

# Check if args are correct
if [[ ! -f $FILE ]]; then
    echo File does not exist
    exit 1
elif [[ $EXTENSION != "tex" ]]; then
    echo $FILE is not a tex file
    exit 1
fi

# Create directory if it doesn't exist
if [ -d ".metafiles" ]; then
  rm -rf .metafiles
fi
mkdir .metafiles

# Run pdflatex and biber with metafiles as in-/output directories
pdflatex -output-directory=.metafiles $NAME
biber --input-directory=.metafiles --output-directory=.metafiles $NAME
pdflatex -output-directory=.metafiles $NAME

# Create a copy to the output PDF
cp .metafiles/$NAME.pdf .
