#!/bin/sh

trap 'update' 5

delim="|"
datetime() { \
	    date "+ %b %d (%a)  %R"
}

volume() { \
	   pamixer --get-volume-human | \
	       awk '{if($0=="muted"){print ""}else{print ""}{print $0}}'
    }

status() { \
	   echo $(volume) $delim $(datetime)
}

update() { \
    xsetroot -name "$(status | tr '\n' ' ')" &
}

while :; do
    update
    sleep 10s &
    wait
done
