#!/bin/bash
set -e

DEFAULT_USERNAME=aropie@hotmail.com
DEFAUL_LENGTH=12

status=$(lpass status | grep Not || true)
if [[ ! -z $status ]]
then
    login=$(lpass login $LPASS_USERNAME)
    if [[ -z $login ]]
    then
	exit 1
    fi
fi

launcher="rofi -dmenu -i hide-scrollbar -p"
name=$($launcher Name)
if [[ -z $name ]]
   then
   exit
fi
username=$(echo -e $DEFAULT_USERNAME | $launcher Username)
url=$($launcher URL)
length=$(echo $DEFAUL_LENGTH | $launcher "Password Length")

group=$(lpass ls --format "%ag" | uniq | grep . | $launcher Group -selected-row -1)
lpass generate -c --sync=now --username=$username --url=$url $group/$name $length
notify-send -t 1500 "LastPass" "Password generated. Copied to clipboard"
