#!/bin/bash

status=$(lpass status | grep Not)
if [[ ! -z $status ]]
then
    login=$(lpass login $LPASS_USERNAME)
    if [[ -z $login ]]
    then
	exit 1
    fi
fi
launcher="rofi -dmenu -p Account -multi-select"
list=$(lpass ls --format "%aN (%au)")

option=$(echo -e "$list" | $launcher | cut -f 1 -d " " | cut -f 2 -d "/")
if [[ ! -z $option ]]
then
    lpass show -cp $option
    notify-send -t 1500 "LastPass" "Password copied to clipboard"
fi
