#!/bin/bash

status=$(lpass status | grep Not)
if [[ ! -z $status ]]
then
    login=$(lpass login $LPASS_USERNAME)
    if [[ -z $login ]]
    then
	exit 1
    fi
fi
launcher="rofi -dmenu -i -hide-scrollbar -p Account"
list=$(lpass ls --format %an)

option=$(echo -e "$list" | $launcher)
lpass show -cp $option
notify-send "LastPass" "Password copied to clipboard"
